
services:
  minf2_julia:
    image: minf2:latest
    container_name: minf2_julia
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256-color
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./:/root/workspace/
    tty: true
    stdin_open: true
    network_mode: "host"
    privileged: true
    ulimits:
      rtprio: 70
      rttime: -1
      memlock: 8428281856
    devices:
      - "/dev:/dev"
    command: /bin/bash
